name: "Build"
on:
  pull_request:
    paths-ignore:
      - 'dist/**'
  push:
    paths-ignore:
      - 'dist/**'

jobs:
  test_ros:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build
    - run: git add -f dist/index.js
    - run: git interpret-trailers --trailer autobuilt
    - run: git commit --amend
    # - run: git commit --author="CI <nobody@github.com>" --message="Autobuild"
    - run: git push
